version: "3.8"

services:
  drupal:
    build:
      context: ./drupal-itc
      dockerfile: Dockerfile
    ports:
      - "${DRUPAL_PORT}:80"
    volumes:
      - ./drupal-itc:/var/www/html:cached
      - ./drupal-itc/docker/default:/var/www/html/web/sites/default
      # - /var/www/html/vendor
      # - /var/www/html/web/core
      # - /var/www/html/web/modules/contrib
    environment:
      - APACHE_SERVER_NAME=app1.example.com
      - VIRTUAL_HOST=app1.example.com
  nextjs:
    build:
      context: ./next-itc
      dockerfile: Dockerfile
    ports:
      - "${NEXT_PORT}:3000"
    command: sh -c "yarn dev"
    volumes:
      - ./next-itc:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_DRUPAL_BASE_URL=http://drupal
      - NEXT_IMAGE_DOMAIN=drupal
      - NEXT_SVG_DOMAIN=http://localhost:${DRUPAL_PORT}
      - DRUPAL_REVALIDATE_SECRET=secret
    depends_on:
      - drupal
